apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: lavanya986/javaapp:v1  # Replace with your actual image name and tag
        ports:
        - containerPort: 8080  # Assuming the Java application runs on port 8080, adjust if needed
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"  # Optional: Configure memory settings for the Java app if needed
